# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import newsApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_auto_20171215_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='promotedImage',
            field=models.ImageField(blank=True, null=True, upload_to=newsApp.models.upload_location),
        ),
        migrations.AddField(
            model_name='story',
            name='tallImage',
            field=models.ImageField(blank=True, null=True, upload_to=newsApp.models.upload_location),
        ),
        migrations.AddField(
            model_name='story',
            name='wideImage',
            field=models.ImageField(blank=True, null=True, upload_to=newsApp.models.upload_location),
        ),
    ]
