# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0006_story_promoted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='stories',
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsApp.category'),
        ),
    ]
