# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0007_auto_20171217_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='extraWideImage',
        ),
        migrations.RemoveField(
            model_name='story',
            name='thumbnailImage',
        ),
        migrations.RemoveField(
            model_name='story',
            name='wideImage',
        ),
    ]
