# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0008_auto_20171217_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
