# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0009_author_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
